export default {
  // screens titles
  APP_NAME: "Peto",
  PETS: "Pets",
  DETAILS: "Details",
  REGISTER: "Register",
  ADD_PET: "Add Pet",
  SUBMIT: "Submit",
  MENU: "Menu",
  COMMIT_USER_EDIT: "Edit user",
  SETTINGS: "Settings",

  // greetings
  GOOD_MORNING: "Good morning",
  GOOD_AFTERNOON: "Good afternoon",
  GOOD_EVNING: "Good evning",
  GOOD_NIGHT: "Good night",

  NAME: "Name",
  TYPE: "Type",
  AMOUNT: "Amount",
  USER_NAME: "Username",
  PASSWORD: "Password",
  NEW_PASSWORD: "New password",
  CONFIRM_PASSWORD: "Confirm password",
  DELETE: "Delete",
  CANCEL: "Cancel",
  CONFIRM: "Confirm",
  LOGIN: "Login",
  PET_NAME: "Pet name",
  PET_TYPE: "Type",
  DISCONNECT: "Disconnect",
  YES: "Yes",
  NO: "No",
  SCHEDULE_NAME: "Meal name",
  TIME: "Time",
};
